import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import axiosInstance, { setToken } from '@/_baseService';
import { AuthResponse } from '@/_api/auth/types';
import auth from '@/_api/auth';
import { Providers } from '@/app/_context/Providers';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { access_token } = await axiosInstance
    .post<AuthResponse>(
      auth.token,
      `grant_type=client_credentials&client_id=${process.env['CLIENT_ID']}&client_secret=${process.env['CLIENT_SECRET']}`,
    )
    .then(({ data }) => data);

  setToken(access_token);

  return (
    <html lang="en">
      <body className={`${roboto.className}  antialiased text-sm md:text-base`}>
        <div className="Root">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
